[project]
name = "ncagg"
version = "0.8.19"
dependencies = [
    "cerberus",
    "click",
    "numpy",
    "netCDF4",
]
requires-python = ">= 3.8"
authors = [
    {name = "Stefan Codrescu",email = "stefan.codrescu@noaa.gov"},
]
description = "Utility for aggregation of NetCDF data."
readme = "README.md"
license = {text = "MIT"}
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Documentation = "http://ncagg.readthedocs.io/en/latest/"
Homepage = "https://github.com/5tefan/ncagg"

[project.scripts]
ncagg = "ncagg.cli:cli"